adding freework scraper

diff --git a/.github/workflows/scrap.yaml b/.github/workflows/scrap.yaml
--- a/.github/workflows/scrap.yaml
+++ b/.github/workflows/scrap.yaml
@@ -1,4 +1,4 @@
-name: Scrap freework
+name: Scrap Workflow
 
 on:
   push:
@@ -8,29 +8,25 @@ on:
     branches:
       - main
   schedule:
-    # Exécution toutes les heures
     - cron: '0 * * * *'
 
 jobs:
   run-scraper:
     runs-on: ubuntu-latest
     steps:
-      # Étape 1 : Checkout du code
       - name: Checkout code
-        uses: actions/checkout@v2
+        uses: actions/checkout@v4
 
-      # Étape 2 : Installer les dépendances Python
       - name: Set up Python
-        uses: actions/setup-python@v2
+        uses: actions/setup-python@v4
         with:
-          python-version: '3.11'
+          python-version: '3.8.18' # Specify exact version for consistency
 
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
-          pip install -r requirements.txt
+          if [ -f requirements.txt ]; then pip install -r requirements.txt; else echo "requirements.txt not found"; exit 1; fi
 
-      # Étape 3 : Définir les variables d'environnement secrètes
       - name: Set environment variables
         env:
           MONGO_COLLECTION: ${{ secrets.MONGO_COLLECTION }}
@@ -39,5 +35,12 @@ jobs:
           MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
           MONGO_USER: ${{ secrets.MONGO_USER }}
         run: |
-          echo "Running scraper script"
-          python main.py
+          echo "MONGO_COLLECTION: $MONGO_COLLECTION"
+          echo "MONGO_DB: $MONGO_DB"
+          echo "MONGO_HOST: $MONGO_HOST"
+          echo "MONGO_USER: $MONGO_USER"
+          if [ -z "$MONGO_COLLECTION" ] || [ -z "$MONGO_DB" ] || [ -z "$MONGO_HOST" ] || [ -z "$MONGO_USER" ] || [ -z "$MONGO_PASSWORD" ]; then
+            echo "Error: One or more environment variables are unset"
+            exit 1
+          fi
+          python main.py || { echo "Script failed with exit code $?"; exit 1; }
